openapi: 3.0.3
info:
  title: 계좌 이체 API
  description: 뱅킹 앱의 계좌 이체 기능을 위한 REST API 명세서
  version: 1.0.0
  contact:
    name: Banking App Development Team
    email: dev@bankingapp.com

servers:
  - url: http://localhost:8000
    description: 개발 서버

paths:
  /api/v1/banks:
    get:
      summary: 지원 은행 목록 조회
      description: 이체 가능한 은행 목록을 조회합니다.
      operationId: getBanks
      tags:
        - Banks
      responses:
        '200':
          description: 은행 목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bank'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/v1/transfers:
    post:
      summary: 이체 실행
      description: 계좌 이체를 실행합니다.
      operationId: createTransfer
      tags:
        - Transfers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '201':
          description: 이체 요청 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '422':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalError'

    get:
      summary: 이체 내역 조회
      description: 사용자의 이체 내역을 조회합니다.
      operationId: getTransfers
      tags:
        - Transfers
      parameters:
        - name: page
          in: query
          description: 페이지 번호 (1부터 시작)
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: 페이지당 항목 수
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: status
          in: query
          description: 이체 상태 필터
          required: false
          schema:
            $ref: '#/components/schemas/TransferStatus'
        - name: from_date
          in: query
          description: 조회 시작일 (YYYY-MM-DD)
          required: false
          schema:
            type: string
            format: date
        - name: to_date
          in: query
          description: 조회 종료일 (YYYY-MM-DD)
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: 이체 내역 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferListResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/v1/transfers/{transfer_id}:
    get:
      summary: 이체 상세 조회
      description: 특정 이체의 상세 정보를 조회합니다.
      operationId: getTransferDetail
      tags:
        - Transfers
      parameters:
        - name: transfer_id
          in: path
          description: 이체 ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 이체 상세 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferDetail'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/v1/transfers/{transfer_id}/status:
    get:
      summary: 이체 상태 조회
      description: 이체의 현재 처리 상태를 조회합니다.
      operationId: getTransferStatus
      tags:
        - Transfers
      parameters:
        - name: transfer_id
          in: path
          description: 이체 ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 이체 상태 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferStatusResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/v1/account/transfer-limits:
    get:
      summary: 이체 한도 조회
      description: 현재 계좌의 이체 한도 정보를 조회합니다.
      operationId: getTransferLimits
      tags:
        - Account
      responses:
        '200':
          description: 이체 한도 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferLimits'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/v1/transfers/validate:
    post:
      summary: 이체 정보 사전 검증
      description: 이체 실행 전 입력 정보의 유효성을 검증합니다.
      operationId: validateTransfer
      tags:
        - Transfers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferValidationRequest'
      responses:
        '200':
          description: 검증 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'
        '400':
          $ref: '#/components/responses/BadRequest'
        '422':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  schemas:
    Bank:
      type: object
      required:
        - id
        - code
        - name
        - transfer_fee
        - is_internal
      properties:
        id:
          type: string
          format: uuid
          description: 은행 고유 식별자
        code:
          type: string
          description: 은행 코드
          example: "004"
        name:
          type: string
          description: 은행명
          example: "국민은행"
        transfer_fee:
          type: number
          format: decimal
          description: 이체 수수료
          example: 500.00
        is_internal:
          type: boolean
          description: 내부 은행 여부
          example: false

    TransferRequest:
      type: object
      required:
        - to_account_number
        - recipient_name
        - amount
      properties:
        to_account_number:
          type: string
          description: 수취 계좌번호
          pattern: '^[0-9]{10,20}$'
          example: "1234567890123456"
        to_bank_id:
          type: string
          format: uuid
          description: 수취 은행 ID (내부 이체시 생략 가능)
          nullable: true
        recipient_name:
          type: string
          description: 받는분 성명
          minLength: 2
          maxLength: 100
          example: "홍길동"
        amount:
          type: number
          format: decimal
          description: 이체 금액
          minimum: 1
          maximum: 1000000
          example: 50000.00
        memo:
          type: string
          description: 이체 메모
          maxLength: 200
          nullable: true
          example: "용돈"

    TransferResponse:
      type: object
      required:
        - transfer_id
        - status
        - amount
        - fee
        - estimated_completion_time
      properties:
        transfer_id:
          type: string
          format: uuid
          description: 이체 고유 식별자
        status:
          $ref: '#/components/schemas/TransferStatus'
        amount:
          type: number
          format: decimal
          description: 이체 금액
        fee:
          type: number
          format: decimal
          description: 이체 수수료
        estimated_completion_time:
          type: string
          format: date-time
          description: 예상 완료 시간
        message:
          type: string
          description: 응답 메시지
          example: "이체가 정상적으로 접수되었습니다."

    TransferStatus:
      type: string
      enum:
        - PENDING
        - IN_PROGRESS
        - COMPLETED
        - FAILED
        - CANCELLED
      description: |
        이체 상태:
        - PENDING: 처리 대기중
        - IN_PROGRESS: 처리중
        - COMPLETED: 완료
        - FAILED: 실패
        - CANCELLED: 취소됨

    TransferListResponse:
      type: object
      required:
        - transfers
        - pagination
      properties:
        transfers:
          type: array
          items:
            $ref: '#/components/schemas/TransferSummary'
        pagination:
          $ref: '#/components/schemas/Pagination'

    TransferSummary:
      type: object
      required:
        - id
        - to_account_number
        - recipient_name
        - amount
        - status
        - created_at
      properties:
        id:
          type: string
          format: uuid
        to_account_number:
          type: string
          description: 수취 계좌번호 (마스킹됨)
          example: "1234****1234"
        recipient_name:
          type: string
          description: 받는분 성명
        amount:
          type: number
          format: decimal
          description: 이체 금액
        fee:
          type: number
          format: decimal
          description: 이체 수수료
        status:
          $ref: '#/components/schemas/TransferStatus'
        bank_name:
          type: string
          description: 수취 은행명
          nullable: true
        created_at:
          type: string
          format: date-time
          description: 이체 요청 시간

    TransferDetail:
      allOf:
        - $ref: '#/components/schemas/TransferSummary'
        - type: object
          properties:
            from_account_number:
              type: string
              description: 송금 계좌번호 (마스킹됨)
            full_to_account_number:
              type: string
              description: 수취 계좌번호 (전체)
            memo:
              type: string
              description: 이체 메모
              nullable: true
            error_message:
              type: string
              description: 오류 메시지 (실패시)
              nullable: true
            completed_at:
              type: string
              format: date-time
              description: 완료 시간
              nullable: true
            transaction_id:
              type: string
              format: uuid
              description: 연관된 거래 내역 ID
              nullable: true

    TransferStatusResponse:
      type: object
      required:
        - transfer_id
        - status
        - created_at
      properties:
        transfer_id:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/TransferStatus'
        progress_message:
          type: string
          description: 진행 상황 메시지
          example: "타행으로 이체 중입니다..."
        created_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
          nullable: true
        estimated_completion:
          type: string
          format: date-time
          description: 예상 완료 시간
          nullable: true

    TransferLimits:
      type: object
      required:
        - daily_limit
        - remaining_daily_limit
        - per_transaction_limit
      properties:
        daily_limit:
          type: number
          format: decimal
          description: 일일 이체 한도
          example: 5000000.00
        remaining_daily_limit:
          type: number
          format: decimal
          description: 잔여 일일 한도
          example: 3000000.00
        per_transaction_limit:
          type: number
          format: decimal
          description: 1회 이체 한도
          example: 1000000.00
        used_today:
          type: number
          format: decimal
          description: 오늘 사용한 이체 금액
          example: 2000000.00

    TransferValidationRequest:
      type: object
      required:
        - to_account_number
        - amount
      properties:
        to_account_number:
          type: string
          description: 수취 계좌번호
        to_bank_id:
          type: string
          format: uuid
          description: 수취 은행 ID
          nullable: true
        amount:
          type: number
          format: decimal
          description: 이체 금액

    ValidationResult:
      type: object
      required:
        - is_valid
        - estimated_fee
      properties:
        is_valid:
          type: boolean
          description: 검증 결과
        estimated_fee:
          type: number
          format: decimal
          description: 예상 수수료
        warnings:
          type: array
          items:
            type: string
          description: 경고 메시지
          example: ["일일 한도의 80%를 초과합니다"]
        errors:
          type: array
          items:
            type: string
          description: 오류 메시지
          example: ["잔액이 부족합니다"]

    Pagination:
      type: object
      required:
        - current_page
        - total_pages
        - total_items
        - has_next
        - has_previous
      properties:
        current_page:
          type: integer
          description: 현재 페이지
          example: 1
        total_pages:
          type: integer
          description: 전체 페이지 수
          example: 10
        total_items:
          type: integer
          description: 전체 항목 수
          example: 150
        has_next:
          type: boolean
          description: 다음 페이지 존재 여부
        has_previous:
          type: boolean
          description: 이전 페이지 존재 여부

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: 오류 코드
        message:
          type: string
          description: 오류 메시지
        details:
          type: object
          description: 상세 오류 정보
          nullable: true

  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "INVALID_REQUEST"
            message: "요청 형식이 올바르지 않습니다"

    ValidationError:
      description: 입력값 검증 오류
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "VALIDATION_ERROR"
            message: "입력값이 유효하지 않습니다"
            details:
              amount: ["이체 금액은 1원 이상이어야 합니다"]

    NotFound:
      description: 리소스를 찾을 수 없음
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "NOT_FOUND"
            message: "요청한 이체 정보를 찾을 수 없습니다"

    InternalError:
      description: 서버 내부 오류
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "INTERNAL_ERROR"
            message: "서버 내부 오류가 발생했습니다"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT 토큰 기반 인증 (향후 구현 예정)

# 현재는 인증 없이 개발하지만, 향후 확장을 위해 보안 스키마 정의
# security:
#   - BearerAuth: []

tags:
  - name: Transfers
    description: 이체 관련 API
  - name: Banks
    description: 은행 정보 관련 API
  - name: Account
    description: 계좌 정보 관련 API